---
apiVersion: v2
name: prometheus
description: Prometheus
type: application
version: 0.1.0
dependencies:
  - name: prometheus
    version: 27.45.x
    repository: https://prometheus-community.github.io/helm-charts
