apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: operator-oauth
  namespace: sops
spec:
  secretTemplates:
    - name: operator-oauth
      namespace: tailscale
      stringData:
        client_id: ENC[AES256_GCM,data:pDhYI5A/ZX4SGkwGR5BiFPY=,iv:9zJGcrX2n606cypiX5kHfpxQ7EEmPLBTNe1ai5F3rSo=,tag:hflfTNEFYPiyGjwyLzP2kg==,type:str]
        client_secret: ENC[AES256_GCM,data:fQvbdgHgo7ohsiG77zLm5hA//95ht+PGnSYVbWtoms1AH3xMbpXGcRCXXEivjLalqhfyiNgCZI6YJ7RG9S7Gng==,iv:DxkQbyglXyR7QTWQMxzvYSOavUtJTFqzVZ5HwcgNdvY=,tag:1UeFv3g6AAZxRLnU/QChXw==,type:str]
sops:
  age:
    - recipient: age1vqqd3t7f5ga8fjue9w27alqw7utnm7wdaze627y4udl3ntsgt37sz8h4rz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTG02RU9zWkdDWkhOTWNS
        VThvMXpSbGR0RkVidnJpRElRMU9TYWxVOEJrClczd3hKSEJGL1VlSkhKSERGSEQ4
        WHR4R1dLblNOOXZTaEU0WlNuRHRrc3cKLS0tIGdYRUxXNStGZ1U1R1JuWWFyOWRQ
        eEczdjU0NEJhamlnZ3A2ek5CQ044Vk0KftS2S/hqYLLDIZdPfszvBVxllQjeJ8j6
        CBxKnkuT1vtekFqVOcXJwp1pY7XgOZ7xrHsGpiXBQUSrX3wifSSZEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T12:15:39Z"
  mac: ENC[AES256_GCM,data:BHyXEDEIcqDzg+IOJScy9+5WhGhJiYDgYlfNYuzhB/R5YNuWLh/XA2NUDWZWdlHMheXlnGrx0EfrHNq+2JEIwu9nQl/0ZIDlTwt8Sb43pvMR3bMe5t57Kyx85BlVpWPSX2r5JSyGnGhX+QU+iQdUf9uRyyuF4C0TiwmxVRF6+uM=,iv:mJHvvW582jf/ugGYZFb0btgDawUpRgiq+7wGmI6hlM4=,tag:kmoSPsHC8jRFrmHafFCxmA==,type:str]
  encrypted_regex: ^(stringData|data|binaryData)$
  version: 3.11.0
