apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
    namespace: sops
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:GuNKGN9rSVbQoA7ffYA=,iv:HoOtj9hVit/NFfHVt3T1umdKnEJTu+kC/fHycimv07c=,tag:5n/36FRJMLNCrwHN8k1e2w==,type:str]
          namespace: ENC[AES256_GCM,data:WkD/t/HcA8ER,iv:lSIID7q8zjsI6Yewxy+oW2CiIA+DCZW/ZErEETb5S2k=,tag:z85Xt1TRMih8nTp/tB+9vQ==,type:str]
          stringData:
            client_id: ENC[AES256_GCM,data:DWLPSy+3Q+fkznPzEvrmc8U=,iv:L3p1M+n/rzBJI+QuG9vnX7uovn8VHxqV1FLVL92zRvo=,tag:NuEuPln7QKFS3nfqyXSekA==,type:str]
            client_secret: ENC[AES256_GCM,data:dbLcKjN7NzIqBxC35yy/xsUKmj8DueAmYd1mqO4YJi/C43MEyuKoR3ECa2j50P/3qdcxdao1bn/41IZItYV72Q==,iv:xxi6zQxRdp8WTUHinh0NqqkkP61VRp7zRZzLA6TAxYM=,tag:S/mPCWyQpscsyvkxmT/w+w==,type:str]
sops:
    age:
        - recipient: age1vqqd3t7f5ga8fjue9w27alqw7utnm7wdaze627y4udl3ntsgt37sz8h4rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMjdGRE5Ha2pFWjhUZXNN
            V2V4QzBXZ1RzRVZXRTltRjZFZzJsVWw4clhjCjZlQUxTbDZhcU9LZER2M3ZoeUVC
            N0V2UHJmRXhDNkZUSnZ4a3ZJUllkRTQKLS0tIGNDNmUvNWg0enN5YkIrdlhpczZi
            ejZkem0rWXI3dnlIZGlFNENXbVFqajQKKtBMIoDyX4ddBK3LWSpmzh0uKj17cd/n
            t38j+3dpc71FAhMwD14NDxenHucSeNmDKOkuW5nE/YuLNkkfk0gRSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T11:17:39Z"
    mac: ENC[AES256_GCM,data:/MUmnNNiIt3fhLHYBlWv6qdN7rEJChLJ3UvFktanUY5JrvcxZr+MaufM49iBG0sAYR0cOh13vadEQEbPE0zQ6CGES2RMd0G2/DsHRGlUQ1HlGh+TBmBeXbC9S3sToNLVQYIg5vtCOgg+6O5BreyTgNc3UE0ETTVcqL5K6ycJFu8=,iv:uQCdFWdanncrOtLjt9kkHLFa8MANCCu4TRwilIXwR14=,tag:5ve4qL2qgaRdbfJvQqmLNw==,type:str]
    encrypted_regex: ^(secretTemplates|stringData|data|binaryData)$
    version: 3.11.0
