---
apiVersion: v2
name: tailscale-operator
description: Tailscale operator
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: tailscale-operator
    version: 1.70.x
    repository: https://pkgs.tailscale.com/helmcharts
