---
apiVersion: v2
name: tailscale-operator
description: Tailscale operator
type: application
version: 0.1.0
dependencies:
  - name: tailscale-operator
    version: 1.90.x
    repository: https://pkgs.tailscale.com/helmcharts
