oauth:
  clientId: ENC[AES256_GCM,data:QMJlieIeo/hnp5aXJQkw11I=,iv:jexWfsY0Amzhj/9SF3IPoLt35pk8X/4IIYI2FBmtjcY=,tag:6P7GGCyb9YqwNHnNV89ofA==,type:str]
  clientSecret: ENC[AES256_GCM,data:W02vHUdmslG5japvvH/aiOiHzHZQgmjW/xqWHPyBWY4Fm5W5br6f3U1pLaTMyaeGZqwGpdEEwi1lUipm8xDyyQ==,iv:ZbnO4I3iAtF3bI6Vj15gOc9kZTVJj03CVGrRD8s4LEA=,tag:eeU4+/dFy+rnaiccGVSp/A==,type:str]
sops:
  age:
    - recipient: age1vqqd3t7f5ga8fjue9w27alqw7utnm7wdaze627y4udl3ntsgt37sz8h4rz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma1pzeS9qRmduaXBiNHpu
        YVgzelNrVE9JdGlLanBreStiTnFNL2hvNkdvClBqNEFXVGFVRm5HTjlzbmNiNnNE
        d2N6QUxlS0ZPZ3VrZDZwZEdQUzhKYmcKLS0tIFlQN1JmcEluSVY2NnpFSzNFWGND
        ZzhZWEdPdEgvSWxDQlhuQnAzSU14ak0KZKFJU4KIYweMc8rmRwkkeBb1R/WfNEAz
        h61tPOXzQoVTGSFHCiCj3mPktLKKjc2OgkRA3JSD1RQTQYCpa7Smew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T14:50:34Z"
  mac: ENC[AES256_GCM,data:tA0W+Tg02vhXHVPXtVLGK4lRAawVG32S/4BeV4HfG4ukHikM5SZSdBSceMEyo9W7fI01YuhFiKwbg23gvxpU04E05BxludLv0WZNeDEN2baGHxNnwhtLur8+Pf2IensoxCxzFNWwbr8k/sdIdHfIlTPGWsqWNQtp5Tu5L53WnWs=,iv:P2K9EVGRsRBq6buwtftk4HaySMn+BWDUVy4gfm+2g9I=,tag:SRbvUU0bZJx0znB7BFS0AQ==,type:str]
  encrypted_regex: ^(oauth)$
  version: 3.11.0
