---
apiVersion: sops-operator.isindir.github.com/v1alpha1
kind: SopsSecret
metadata:
  name: tailscale-oauth
  namespace: {{ .Release.Namespace }}
spec:
  secretTemplates:
    - name: tailscale-oauth
      type: Opaque
      stringData:
        clientId: {{ .Values.oauth.clientId | quote }}
        clientSecret: {{ .Values.oauth.clientSecret | quote }}
