---
config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/rickyhugo/hugoplanet-infra-lab.git
      targetRevision: main

applications:
  - name: argo-cd
    namespace: argocd
    prune: false
    tool:
      helm:
        releaseName: argo-cd
  - name: sops-secrets-operator
    namespace: sops
    annotations:
      argocd.argoproj.io/sync-wave: "0"
    tool:
      helm:
        releaseName: sops-secrets-operator
  - name: cluster-secrets
    namespace: sops
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    tool:
      helm:
        releaseName: cluster-secrets
  - name: prometheus
    namespace: monitoring
    tool:
      helm:
        releaseName: prometheus
  - name: tailscale-operator
    namespace: tailscale
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    tool:
      helm:
        releaseName: tailscale-operator
