---
config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/rickyhugo/hugoplanet-infra-lab.git
      targetRevision: main

applications:
  - name: argo-cd
    namespace: argocd
    prune: false
    tool:
      helm:
        releaseName: argo-cd
  - name: prometheus
    namespace: monitoring
    tool:
      helm:
        releaseName: prometheus
