---
apiVersion: v2
name: tailscale-load-balancer
description: Tailscale load balancer
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.14.x
    repository: https://kubernetes.github.io/ingress-nginx
