---
apiVersion: v2
name: sops-secrets-operator
description: SOPS Secrets Operator deployment
version: 0.1.0
type: application
appVersion: "1.0"
dependencies:
  - name: sops-secrets-operator
    version: 0.22.0
    repository: https://isindir.github.io/sops-secrets-operator/
