---
age:
  secretName: sops-age-key
  keyFile: key.txt
  mountPath: /etc/sops-age

sops-secrets-operator:
  fullnameOverride: sops-secrets-operator
  namespaced: false
  secretsAsFiles:
    - name: sops-age-key
      mountPath: /etc/sops-age
      secretName: sops-age-key
      items:
        - key: key.txt
          path: key.txt
  extraEnv:
    - name: SOPS_AGE_KEY_FILE
      value: /etc/sops-age/key.txt
